### ISSUE TITLE
My pull request

### ISSUE THREAD

**Issue by Meister1977** [rhornig/anysoftkeyboard-hungarian#12]
Hi, 

Could you please accept my pull request, and then create a new build with it to Google Play. Thanks.

Jeleztem az Anysoft hivatalos chat-jában, hogy a pull requestem hónapok óta nem megy be, és úgy néz ki, hogy már nem akarjátok ezt a projectet vinni.

https://gitter.im/AnySoftKeyboard/localization

Mit tudnánk tenni, hogy a kiosztásom bekerüljön? Ha átadjátok a szükséges kulcsokat és a projectet a Anysoftnak, az lenne talán a legjobb megoldás, mert akkor a meglévő Play-es alkalmazást tudnák frissíteni. Ha ezt nem akarjátok, akkor mi legyen?

**Comment by rhornig** [comment]
Bocsánatot kérek. Nagyon sok egyéb dolog összejött és nem volt meg a rendes
build környezet amivel releas-t tudok csinálni így mindig halogattam a
dolgot.
Most végre összeszedtem magam és csináltam egy release-t.

Sajnos a kulcs átadás nem fog menni, mivel elég amatőr módon több
alkalmazáshoz is ugyanazt a kulcsot kezdetem használni amikor release-eltem
őket :(
Viszont azért ha vannak változások és pull request-ek amik le vannak
tesztelve, akkor arra talán lesz időm, hogy egy release-t néha csinálja ha
elég kitartóan zargatsz :)
Pláne most hogy már nem kell talán a setup-val bajlódnom újra...

Rudi

**Comment by Meister1977** [comment]
Szia!

Rendben, köszi!

Ha aktualizálod a forrást a buildhez szükséges dolgokkal, az is sokat segíthet majd. (Kivéve a kulcsok, persze.)
Másik meg, hogy abból a szótárból van új verzió, amit használtál, de egyszerűen nem jövök rá, azt hogyan kellene beforgatni ide, hogy jó legyen.
Pedig állítólag elég jó, hiszen az elmúlt vagy 10 év fejlesztései mentek bele.

**Comment by rhornig** [comment]
Főleg a saját lokális környezetem volt problémás. Ami a repo-ba fenn vann, az pont az amivel fordítottam most az új verziót. a local.properties és a keytore file kivételével.
